# Generated by Django 5.2.16 on 2026-07-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="affiliation_type",
            field=models.CharField(
                choices=[
                    ("NOT_INFORMED", "Não informado"),
                    ("STUDENT", "Aluno"),
                    ("PROFESSOR", "Professor"),
                    ("TECHNICAL_STAFF", "Técnico-administrativo"),
                ],
                default="NOT_INFORMED",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="institutional_unit",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="usesession",
            name="affiliation_type",
            field=models.CharField(
                choices=[
                    ("NOT_INFORMED", "Não informado"),
                    ("STUDENT", "Aluno"),
                    ("PROFESSOR", "Professor"),
                    ("TECHNICAL_STAFF", "Técnico-administrativo"),
                ],
                default="NOT_INFORMED",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="usesession",
            name="institutional_unit",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
