# Generated by Django 5.2.16 on 2026-07-26 05:52

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.operations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("computers", "0001_initial"),
        ("operations", "0002_reservation_affiliation_type_and_more"),
    ]

    operations = [
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("status", "CONFIRMED")),
                expressions=[
                    ("computer", "="),
                    (
                        models.Func(
                            models.F("starts_at"),
                            models.F("ends_at"),
                            models.Value("[)"),
                            function="TSTZRANGE",
                            output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                        ),
                        "&&",
                    ),
                ],
                name="reservation_computer_no_overlap",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("status", "CONFIRMED")),
                expressions=[
                    ("user_reference", "="),
                    (
                        models.Func(
                            models.F("starts_at"),
                            models.F("ends_at"),
                            models.Value("[)"),
                            function="TSTZRANGE",
                            output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                        ),
                        "&&",
                    ),
                ],
                name="reservation_user_no_overlap",
            ),
        ),
    ]
