# Generated by Django 5.2.16 on 2026-07-27 04:56

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("computers", "0001_initial"),
        ("operations", "0003_reservation_reservation_computer_no_overlap_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="computerallocation",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                expressions=[
                    ("computer", "="),
                    (
                        models.Func(
                            models.F("started_at"),
                            models.F("ended_at"),
                            models.Value("[)"),
                            function="TSTZRANGE",
                            output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                        ),
                        "&&",
                    ),
                ],
                name="allocation_computer_no_overlap",
            ),
        ),
    ]
