# Generated by Django 5.2.17 on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0004_computerallocation_allocation_computer_no_overlap"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="invalidated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="invalidated_by_profile",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ROOM_USER", "Usuário da Sala"),
                    ("INTERN", "Monitor da Sala"),
                    ("LIBRARY_SUPERVISOR", "Supervisor da Biblioteca"),
                    ("SYSTEM_ADMIN", "Administrador do Sistema"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="invalidation_reason",
            field=models.TextField(blank=True),
        ),
    ]
