# Generated by Django 5.2.17 on 2026-08-06 23:36

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def normalize_reservations_and_profiles(apps, schema_editor):
    BookingPolicy = apps.get_model("configuration", "BookingPolicy")
    Reservation = apps.get_model("operations", "Reservation")
    UseSession = apps.get_model("operations", "UseSession")

    policies = list(BookingPolicy.objects.order_by("valid_from", "created_at", "pk"))
    if Reservation.objects.exists() and not policies:
        first_reservation = Reservation.objects.order_by("starts_at", "pk").first()
        policies = [
            BookingPolicy.objects.create(
                valid_from=timezone.localdate(first_reservation.starts_at),
                cancellation_limit_minutes=0,
                max_future_reservations_per_user=1,
            )
        ]

    for reservation in Reservation.objects.order_by("pk").iterator(chunk_size=500):
        target_date = timezone.localdate(reservation.starts_at)
        policy = next(
            (
                item
                for item in reversed(policies)
                if item.valid_from <= target_date
                and (item.valid_until is None or item.valid_until >= target_date)
            ),
            None,
        )
        policy = policy or policies[0]
        reservation.booking_policy_id = policy.pk

        update_fields = ["booking_policy"]
        if reservation.status == "NO_SHOW":
            reservation.status = "CANCELLED"
            reservation.cancelled_at = (
                reservation.no_show_at or reservation.check_in_deadline_at
            )
            reservation.cancelled_by_profile = "SYSTEM_ADMIN"
            reservation.cancellation_reason = "Prazo de check-in expirado."
            update_fields.extend(
                [
                    "status",
                    "cancelled_at",
                    "cancelled_by_profile",
                    "cancellation_reason",
                ]
            )
        elif reservation.status == "INVALIDATED":
            reservation.status = "CANCELLED"
            reservation.cancelled_at = (
                reservation.invalidated_at or reservation.updated_at
            )
            reservation.cancelled_by_profile = (
                reservation.invalidated_by_profile or "SYSTEM_ADMIN"
            )
            reservation.cancellation_reason = (
                reservation.invalidation_reason
                or "Cancelada por alteração operacional."
            )
            update_fields.extend(
                [
                    "status",
                    "cancelled_at",
                    "cancelled_by_profile",
                    "cancellation_reason",
                ]
            )
        if reservation.created_by_profile == "INTERN":
            reservation.created_by_profile = "ROOM_MONITOR"
            update_fields.append("created_by_profile")
        if reservation.cancelled_by_profile == "INTERN":
            reservation.cancelled_by_profile = "ROOM_MONITOR"
            update_fields.append("cancelled_by_profile")
        reservation.save(update_fields=list(dict.fromkeys(update_fields)))

    UseSession.objects.filter(entry_recorded_by_profile="INTERN").update(
        entry_recorded_by_profile="ROOM_MONITOR"
    )
    UseSession.objects.filter(exit_recorded_by_profile="INTERN").update(
        exit_recorded_by_profile="ROOM_MONITOR"
    )


def restore_operation_profiles(apps, schema_editor):
    Reservation = apps.get_model("operations", "Reservation")
    UseSession = apps.get_model("operations", "UseSession")
    Reservation.objects.filter(created_by_profile="ROOM_MONITOR").update(
        created_by_profile="INTERN"
    )
    Reservation.objects.filter(cancelled_by_profile="ROOM_MONITOR").update(
        cancelled_by_profile="INTERN"
    )
    UseSession.objects.filter(entry_recorded_by_profile="ROOM_MONITOR").update(
        entry_recorded_by_profile="INTERN"
    )
    UseSession.objects.filter(exit_recorded_by_profile="ROOM_MONITOR").update(
        exit_recorded_by_profile="INTERN"
    )


class Migration(migrations.Migration):
    dependencies = [
        (
            "configuration",
            "0007_remove_bookingpolicy_one_active_booking_policy_and_more",
        ),
        ("operations", "0008_enforce_model_c_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="booking_policy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="configuration.bookingpolicy",
            ),
        ),
        migrations.RunPython(
            normalize_reservations_and_profiles,
            restore_operation_profiles,
        ),
        migrations.AlterField(
            model_name="reservation",
            name="booking_policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="configuration.bookingpolicy",
            ),
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="invalidated_at",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="invalidated_by_profile",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="invalidation_reason",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="no_show_at",
        ),
        migrations.AlterField(
            model_name="computerallocation",
            name="end_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SWITCH", "Troca de computador"),
                    ("COMPUTER_UNAVAILABLE", "Computador indisponível"),
                    ("SESSION_FINISHED", "Sessão encerrada"),
                    ("TIME_LIMIT_REACHED", "Limite de tempo atingido"),
                    ("ADMIN_CORRECTION", "Correção administrativa"),
                    ("CANCELLED", "Cancelada"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="cancelled_by_profile",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ROOM_USER", "Usuário da Sala"),
                    ("ROOM_MONITOR", "Monitor da Sala"),
                    ("LIBRARY_SUPERVISOR", "Supervisor da Biblioteca"),
                    ("SYSTEM_ADMIN", "Administrador do Sistema"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="created_by_profile",
            field=models.CharField(
                choices=[
                    ("ROOM_USER", "Usuário da Sala"),
                    ("ROOM_MONITOR", "Monitor da Sala"),
                    ("LIBRARY_SUPERVISOR", "Supervisor da Biblioteca"),
                    ("SYSTEM_ADMIN", "Administrador do Sistema"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("CONFIRMED", "Confirmada"),
                    ("CANCELLED", "Cancelada"),
                    ("USED", "Utilizada"),
                ],
                default="CONFIRMED",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="usesession",
            name="entry_recorded_by_profile",
            field=models.CharField(
                choices=[
                    ("ROOM_USER", "Usuário da Sala"),
                    ("ROOM_MONITOR", "Monitor da Sala"),
                    ("LIBRARY_SUPERVISOR", "Supervisor da Biblioteca"),
                    ("SYSTEM_ADMIN", "Administrador do Sistema"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="usesession",
            name="exit_recorded_by_profile",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ROOM_USER", "Usuário da Sala"),
                    ("ROOM_MONITOR", "Monitor da Sala"),
                    ("LIBRARY_SUPERVISOR", "Supervisor da Biblioteca"),
                    ("SYSTEM_ADMIN", "Administrador do Sistema"),
                ],
                max_length=32,
            ),
        ),
    ]
