@startuml
left to right direction

skinparam packageStyle rectangle
skinparam actorStyle awesome

actor "Monitor da Sala" as Monitor

rectangle "Sistema de Controle de Uso da Sala de Informática da Biblioteca da UFAC" {

  package "Acompanhamento da sala" {
    usecase "Consultar sessões ativas" as UC01
    usecase "Consultar computadores disponíveis,\nocupados ou indisponíveis" as UC02
  }

  package "Controle de computadores" {
    usecase "Alterar status\ndo computador" as UC03
  }

  package "Ocorrências" {
    usecase "Registrar ocorrência" as UC04
    usecase "Consultar ocorrências" as UC05
  }

  package "Registros" {
    usecase "Consultar histórico\nde uso da sala" as UC06
    usecase "Corrigir registro\nde uso" as UC07
  }
}

Monitor --> UC01
Monitor --> UC02
Monitor --> UC03
Monitor --> UC04
Monitor --> UC05
Monitor --> UC06
Monitor --> UC07
@enduml
