# Generated by Django 5.2.17 on 2026-08-06 23:36

from django.db import migrations, models


def rename_profile(apps, schema_editor):
    apps.get_model("audit", "AuditEvent").objects.filter(actor_profile="INTERN").update(
        actor_profile="ROOM_MONITOR"
    )


def restore_profile(apps, schema_editor):
    apps.get_model("audit", "AuditEvent").objects.filter(
        actor_profile="ROOM_MONITOR"
    ).update(actor_profile="INTERN")


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(rename_profile, restore_profile),
        migrations.AlterField(
            model_name="auditevent",
            name="actor_profile",
            field=models.CharField(
                choices=[
                    ("ROOM_USER", "Usuário da Sala"),
                    ("ROOM_MONITOR", "Monitor da Sala"),
                    ("LIBRARY_SUPERVISOR", "Supervisor da Biblioteca"),
                    ("SYSTEM_ADMIN", "Administrador do Sistema"),
                ],
                max_length=32,
            ),
        ),
    ]
