# Generated by Django 5.2.17 on 2026-08-05

import uuid

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0002_shift_series_key"),
        ("operations", "0003_reservation_reservation_computer_no_overlap_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatingSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "series_key",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular"),
                            ("TEMPORARY", "Temporário"),
                        ],
                        max_length=16,
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by_profile",
                    models.CharField(
                        choices=[
                            ("ROOM_USER", "Usuário da Sala"),
                            ("INTERN", "Monitor da Sala"),
                            ("LIBRARY_SUPERVISOR", "Supervisor da Biblioteca"),
                            ("SYSTEM_ADMIN", "Administrador do Sistema"),
                        ],
                        max_length=32,
                    ),
                ),
            ],
            options={
                "ordering": ["-valid_from", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=[
                            "schedule_type",
                            "is_active",
                            "valid_from",
                            "valid_until",
                        ],
                        name="op_sched_validity_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_until__isnull", True),
                            ("valid_until__gte", models.F("valid_from")),
                            _connector="OR",
                        ),
                        name="operating_schedule_valid_period",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("schedule_type", "REGULAR"),
                            ("valid_until__isnull", False),
                            _connector="OR",
                        ),
                        name="temporary_schedule_requires_end",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        condition=models.Q(("is_active", True)),
                        expressions=[
                            ("schedule_type", "="),
                            (
                                models.Func(
                                    models.F("valid_from"),
                                    models.F("valid_until"),
                                    models.Value("[]"),
                                    function="DATERANGE",
                                    output_field=django.contrib.postgres.fields.ranges.DateRangeField(),
                                ),
                                "&&",
                            ),
                        ],
                        name="operating_schedule_no_same_type_overlap",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OperatingScheduleDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terça-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                ("is_open", models.BooleanField(default=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="configuration.operatingschedule",
                    ),
                ),
            ],
            options={"ordering": ["weekday"]},
        ),
        migrations.CreateModel(
            name="OperatingWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("opens_at", models.TimeField()),
                ("closes_at", models.TimeField()),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "schedule_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="windows",
                        to="configuration.operatingscheduleday",
                    ),
                ),
            ],
            options={"ordering": ["display_order", "opens_at"]},
        ),
        migrations.AddConstraint(
            model_name="operatingscheduleday",
            constraint=models.UniqueConstraint(
                fields=("schedule", "weekday"),
                name="unique_weekday_per_operating_schedule",
            ),
        ),
        migrations.AddConstraint(
            model_name="operatingwindow",
            constraint=models.CheckConstraint(
                condition=models.Q(("opens_at__lt", models.F("closes_at"))),
                name="operating_window_open_before_close",
            ),
        ),
    ]
