# Generated by Django 5.2.17 on 2026-08-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0004_seed_regular_operating_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notice_type",
                    models.CharField(
                        choices=[
                            ("CLOSURE", "Fechamento"),
                            ("SCHEDULE_CHANGE", "Mudança de horário"),
                            ("SPECIAL_HOURS", "Horário especial"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("message", models.TextField()),
                ("effective_from", models.DateField()),
                ("effective_until", models.DateField()),
                ("visible_from", models.DateTimeField()),
                ("visible_until", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by_profile",
                    models.CharField(
                        choices=[
                            ("ROOM_USER", "Usuário da Sala"),
                            ("INTERN", "Monitor da Sala"),
                            ("LIBRARY_SUPERVISOR", "Supervisor da Biblioteca"),
                            ("SYSTEM_ADMIN", "Administrador do Sistema"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "calendar_exception",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notices",
                        to="configuration.calendarexception",
                    ),
                ),
                (
                    "operating_schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notices",
                        to="configuration.operatingschedule",
                    ),
                ),
            ],
            options={"ordering": ["-visible_from", "-created_at"]},
        ),
        migrations.AddIndex(
            model_name="roomnotice",
            index=models.Index(
                fields=["is_active", "visible_from", "visible_until"],
                name="room_notice_visibility_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="roomnotice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_until__gte", models.F("effective_from"))
                ),
                name="room_notice_effective_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="roomnotice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("visible_until__isnull", True),
                    ("visible_until__gte", models.F("visible_from")),
                    _connector="OR",
                ),
                name="room_notice_visible_period",
            ),
        ),
    ]
