# Generated by Django 5.2.17 on 2026-08-06 23:36

from datetime import timedelta

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


def normalize_configuration_data(apps, schema_editor):
    BookingPolicy = apps.get_model("configuration", "BookingPolicy")
    CalendarException = apps.get_model("configuration", "CalendarException")
    OperatingSchedule = apps.get_model("configuration", "OperatingSchedule")
    RoomNotice = apps.get_model("configuration", "RoomNotice")

    CalendarException.objects.filter(exception_type="OPTIONAL_HOLIDAY").update(
        exception_type="CLOSED"
    )
    OperatingSchedule.objects.filter(created_by_profile="INTERN").update(
        created_by_profile="ROOM_MONITOR"
    )
    RoomNotice.objects.filter(created_by_profile="INTERN").update(
        created_by_profile="ROOM_MONITOR"
    )

    policies = list(BookingPolicy.objects.order_by("valid_from", "created_at", "pk"))
    dates = [policy.valid_from for policy in policies]
    if len(dates) != len(set(dates)):
        raise RuntimeError(
            "Existem políticas de reserva com a mesma data inicial; "
            "normalize os dados antes da migração."
        )
    for index, policy in enumerate(policies):
        policy.valid_until = (
            policies[index + 1].valid_from - timedelta(days=1)
            if index + 1 < len(policies)
            else None
        )
        policy.save(update_fields=["valid_until"])


def restore_configuration_profiles_and_active_policy(apps, schema_editor):
    BookingPolicy = apps.get_model("configuration", "BookingPolicy")
    OperatingSchedule = apps.get_model("configuration", "OperatingSchedule")
    RoomNotice = apps.get_model("configuration", "RoomNotice")

    OperatingSchedule.objects.filter(created_by_profile="ROOM_MONITOR").update(
        created_by_profile="INTERN"
    )
    RoomNotice.objects.filter(created_by_profile="ROOM_MONITOR").update(
        created_by_profile="INTERN"
    )
    BookingPolicy.objects.update(is_active=False)
    latest = BookingPolicy.objects.order_by("-valid_from", "-created_at", "-pk").first()
    if latest is not None:
        latest.is_active = True
        latest.save(update_fields=["is_active"])


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0006_remove_configurable_slot_and_tolerance"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bookingpolicy",
            name="one_active_booking_policy",
        ),
        migrations.AddField(
            model_name="bookingpolicy",
            name="valid_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(
            normalize_configuration_data,
            restore_configuration_profiles_and_active_policy,
        ),
        migrations.RemoveField(
            model_name="bookingpolicy",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="calendarexception",
            name="exception_type",
            field=models.CharField(
                choices=[("CLOSED", "Fechado"), ("SPECIAL_HOURS", "Horário especial")],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="operatingschedule",
            name="created_by_profile",
            field=models.CharField(
                choices=[
                    ("ROOM_USER", "Usuário da Sala"),
                    ("ROOM_MONITOR", "Monitor da Sala"),
                    ("LIBRARY_SUPERVISOR", "Supervisor da Biblioteca"),
                    ("SYSTEM_ADMIN", "Administrador do Sistema"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="roomnotice",
            name="created_by_profile",
            field=models.CharField(
                choices=[
                    ("ROOM_USER", "Usuário da Sala"),
                    ("ROOM_MONITOR", "Monitor da Sala"),
                    ("LIBRARY_SUPERVISOR", "Supervisor da Biblioteca"),
                    ("SYSTEM_ADMIN", "Administrador do Sistema"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="bookingpolicy",
            index=models.Index(
                fields=["valid_from", "valid_until"], name="booking_policy_validity_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_until__isnull", True),
                    ("valid_until__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="booking_policy_valid_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingpolicy",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    (
                        models.Func(
                            models.F("valid_from"),
                            models.F("valid_until"),
                            models.Value("[]"),
                            function="DATERANGE",
                            output_field=django.contrib.postgres.fields.ranges.DateRangeField(),
                        ),
                        "&&",
                    )
                ],
                name="booking_policy_no_overlap",
            ),
        ),
    ]
