# Generated by Django 5.2.17 on 2026-09-15 16:24

import datetime

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.expressions
from django.db import migrations, models


def _time_overlaps(first, second):
    return (
        first["start_time"] < second["end_time"]
        and second["start_time"] < first["end_time"]
    )


def _validity_overlaps(first, second):
    first_end = first["valid_until"]
    second_end = second["valid_until"]
    if first_end is not None and second["valid_from"] > first_end:
        return False
    if second_end is not None and first["valid_from"] > second_end:
        return False
    return True


def conflicting_shift_pairs(shifts):
    """Identifica pares de turnos ativos sobrepostos em horário e vigência.

    Somente leitura: nenhum turno é desativado ou corrigido automaticamente.
    """

    pairs = []
    for index, first in enumerate(shifts):
        for second in shifts[index + 1 :]:
            if _time_overlaps(first, second) and _validity_overlaps(first, second):
                pairs.append((first["id"], second["id"]))
    return pairs


def check_conflicting_active_shifts(apps, schema_editor):
    Shift = apps.get_model("configuration", "Shift")
    shifts = list(
        Shift.objects.filter(is_active=True).values(
            "id",
            "name",
            "start_time",
            "end_time",
            "valid_from",
            "valid_until",
        )
    )
    pairs = conflicting_shift_pairs(shifts)
    if pairs:
        identifiers = ", ".join(f"#{first} e #{second}" for first, second in pairs)
        raise RuntimeError(
            "A constraint shift_no_overlap_active não pode ser criada: existem "
            "turnos ativos sobrepostos em horário e vigência "
            f"({identifiers}). Revise esses turnos antes de aplicar a migration."
        )


class Migration(migrations.Migration):
    dependencies = [
        (
            "configuration",
            "0007_remove_bookingpolicy_one_active_booking_policy_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            check_conflicting_active_shifts,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("is_active", True)),
                expressions=[
                    (
                        models.Func(
                            models.ExpressionWrapper(
                                django.db.models.expressions.CombinedExpression(
                                    models.Value(datetime.date(2000, 1, 1)),
                                    "+",
                                    models.F("start_time"),
                                ),
                                output_field=models.DateTimeField(),
                            ),
                            models.ExpressionWrapper(
                                django.db.models.expressions.CombinedExpression(
                                    models.Value(datetime.date(2000, 1, 1)),
                                    "+",
                                    models.F("end_time"),
                                ),
                                output_field=models.DateTimeField(),
                            ),
                            models.Value("[)"),
                            function="TSRANGE",
                            output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                        ),
                        "&&",
                    ),
                    (
                        models.Func(
                            models.F("valid_from"),
                            models.F("valid_until"),
                            models.Value("[]"),
                            function="DATERANGE",
                            output_field=django.contrib.postgres.fields.ranges.DateRangeField(),
                        ),
                        "&&",
                    ),
                ],
                name="shift_no_overlap_active",
            ),
        ),
    ]
