# Generated by Django 5.2.17 on 2026-09-29 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.access.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile",
                    models.CharField(
                        choices=[
                            ("ROOM_USER", "Usuário da Sala"),
                            ("ROOM_MONITOR", "Monitor da Sala"),
                            ("LIBRARY_SUPERVISOR", "Supervisor da Biblioteca"),
                        ],
                        max_length=30,
                    ),
                ),
                ("display_name", models.CharField(max_length=150)),
                (
                    "user_reference",
                    models.CharField(
                        default=apps.access.models.new_user_reference,
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "affiliation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NOT_INFORMED", "Não informado"),
                            ("STUDENT", "Aluno"),
                            ("PROFESSOR", "Professor"),
                            ("TECHNICAL_STAFF", "Técnico-administrativo"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("institutional_unit", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoginIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("CPF", "CPF"), ("MATRICULA", "Matrícula")],
                        max_length=12,
                    ),
                ),
                ("normalized_value", models.CharField(max_length=32, unique=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="access.accessaccount",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="accessaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("profile__in", ["ROOM_USER", "ROOM_MONITOR", "LIBRARY_SUPERVISOR"])
                ),
                name="access_account_supported_profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "affiliation_type__in",
                            ["STUDENT", "PROFESSOR", "TECHNICAL_STAFF"],
                        ),
                        ("profile", "ROOM_USER"),
                        models.Q(("institutional_unit", ""), _negated=True),
                    ),
                    models.Q(
                        models.Q(("profile", "ROOM_USER"), _negated=True),
                        ("affiliation_type__isnull", True),
                        ("institutional_unit", ""),
                    ),
                    _connector="OR",
                ),
                name="access_account_room_identity_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="loginidentifier",
            constraint=models.UniqueConstraint(
                fields=("account", "kind"), name="one_identifier_kind_per_account"
            ),
        ),
    ]
